version: '3'

tasks:
  n8n:full:
    desc: Run n8n AI Stack (full services)
    dir: ./n8n-services
    cmds:
      - docker compose -f docker-compose-full.yml up -d

  n8n:full:down:
    desc: Stop n8n AI Stack (full services)
    dir: ./n8n-services
    cmds:
      - docker compose -f docker-compose-full.yml down

  n8n:ollama:
    desc: Run n8n AI Stack (Ollama only, with profile = cpu)
    dir: ./n8n-services
    cmds:
      - docker compose -f docker-compose-ollama.yml --profile cpu up -d

  n8n:ollama:gpu-nvidia:
    desc: Run n8n AI Stack (Ollama only, with profile = gpu-nvidia)
    dir: ./n8n-services
    cmds:
      - docker compose -f docker-compose-ollama.yml --profile gpu-nvidia up -d

  n8n:ollama:gpu-amd:
    desc: Run n8n AI Stack (Ollama only, with profile = gpu-amd)
    dir: ./n8n-services
    cmds:
      - docker compose -f docker-compose-ollama.yml --profile gpu-amd up -d

  n8n:ollama:down:
    desc: Stop n8n AI Stack (Ollama only)
    dir: ./n8n-services
    cmds:
      - docker compose -f docker-compose-ollama.yml down

  n8n:minimal:
    desc: Run n8n AI Stack (minimal)
    dir: ./n8n-services
    cmds:
      - docker compose -f docker-compose.yml up -d

  n8n:minimal:down:
    desc: Stop n8n AI Stack (minimal)
    dir: ./n8n-services
    cmds:
      - docker compose -f docker-compose.yml down

  n8n:logs:
    desc: Show logs for n8n service (full stack)
    dir: ./n8n-services
    cmds:
      - docker compose -f docker-compose-full.yml logs -f n8n

  n8n:status:
    desc: Show status of all n8n stack containers (full stack)
    dir: ./n8n-services
    cmds:
      - docker compose -f docker-compose-full.yml ps
